#!/usr/bin/env python3
"""Generate the Android build's screen-space scene assets at an integer scale.

The P4 firmware renders at the panel's native 1024x600. Everything upstream of
the base photograph is resolution-independent -- the fitted camera projection
is continuous, the shallow-water solver is world-space, and shading,
refraction and foam are computed per screen pixel -- so the Android build
renders the same scene at a multiple of that resolution and only the base
photograph is resampled. The wave field is computed fresh at the target
resolution on top of it; this is a genuine higher-resolution render, not an
upscale of the P4 output.

Four assets are resolution-dependent and produced here:

  * the base photograph (Lanczos resample -- no new detail, but the wave
    shading, refraction, foam and dither all compute at the new density);
  * the water mask (nearest, bit-exact) and shore-distance field (nearest,
    VALUES UNCHANGED -- the crest phase `shore*5` and foam band `shore<36`
    are calibrated in original units and must stay so);
  * the screen-to-solver map, regenerated by build-ocean-screen-map.py at the
    matching --scale so the Q8.8 solver coordinates land correctly.

The other assets (ocean depth, three cloud atlases) are resolution-independent
and ship straight from the firmware tree.

    scripts/prepare-android-assets.py --scale 2
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "firmware/luminary-background-viewer/assets/runtime"
DST = ROOT / "android/luminary-viewer/scene-assets"
WIDTH, HEIGHT = 1024, 600


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scale", type=int, default=2)
    args = parser.parse_args()
    scale = args.scale
    w, h = WIDTH * scale, HEIGHT * scale
    DST.mkdir(parents=True, exist_ok=True)

    # The Android build shows the whole scene -- island, rocks, lighthouse,
    # sky -- so its base is the full registered photograph, not the P4's
    # sky+water plate (the P4 prints the land physically). source-cropped is
    # the same 1024x600 registration everything else is aligned to.
    from PIL import Image as _Image
    base = _Image.open(ROOT / "scenes/nubble-aligned/compiled/source-cropped.png")
    base.convert("RGB").resize((w, h), _Image.LANCZOS).save(
        DST / "nubble_runtime_base.jpg", quality=95)

    bits = np.unpackbits(
        np.fromfile(SRC / "nubble_runtime_water_mask.bin", dtype=np.uint8),
        bitorder="little").reshape(HEIGHT, WIDTH)
    big = np.repeat(np.repeat(bits, scale, 0), scale, 1)
    np.packbits(big.flatten(), bitorder="little").tofile(
        DST / "nubble_runtime_water_mask.bin")

    shore = np.fromfile(SRC / "nubble_runtime_shore_distance.bin",
                        dtype=np.uint8).reshape(HEIGHT, WIDTH)
    np.repeat(np.repeat(shore, scale, 0), scale, 1).tofile(
        DST / "nubble_runtime_shore_distance.bin")

    # Land mask: the solid, pass-through parts of the photo -- the island and
    # lighthouse (which rise above the horizon) plus the foreground rocks.
    # Sky rows grade everything that is NOT land; below the horizon anything
    # that is not water is land already, so this mask matters most for the
    # island poking into the sky band. Bit-packed like the water mask.
    comp = ROOT / "scenes/nubble-aligned/compiled"
    island = np.array(Image.open(comp / "island-mask.png").convert("L")) > 128
    foreground = np.array(Image.open(comp / "foreground-mask.png").convert("L")) > 128
    land = island | foreground
    # Erode the pass-through region by one source pixel. The island mask was
    # traced a pixel or two into the original photo's bright sky-haze halo, so
    # its outermost rim is photo-sky, not rock. Passed through untouched that
    # rim reads as a hard white outline against the night-graded sky; ceding
    # it back to the sky (which then grades with the rest) trims the edge. The
    # geometry loss is ~2 screen pixels, invisible, and the print covers this
    # boundary anyway.
    from scipy import ndimage as _ndi
    land = _ndi.binary_erosion(land, iterations=1)
    land_big = np.repeat(np.repeat(land, scale, 0), scale, 1)
    np.packbits(land_big.flatten(), bitorder="little").tofile(
        DST / "nubble_runtime_land_mask.bin")

    # The phone's solver runs the 1 m (384x384) grid, so it needs that depth
    # field, not the P4's 192x192. The three cloud atlases stay
    # resolution-independent and ship from the firmware tree.
    import shutil
    shutil.copyfile(ROOT / "tools/ocean-sim/nubble_depth_384x384.bin",
                    DST / "nubble_runtime_ocean_depth.bin")

    subprocess.run(
        [sys.executable, str(ROOT / "scripts/build-ocean-screen-map.py"),
         "--scale", str(scale),
         "--output", str(DST / "nubble_runtime_ocean_map.bin")],
        check=True)

    # Daytime offline-fallback scene: the wall piece cold-starts on a bright
    # day rather than whatever the last live capture happened to be; the live
    # fetch overrides within seconds where there is network.
    import json as _json
    scene = _json.load(open(
        ROOT / "firmware/luminary-background-viewer/assets/v2/nubble-runtime-scene-v1.json"))
    scene["sun"] = {"altitude_deg": 42.0, "azimuth_deg": 170.0,
                    "off_screen": False, "state": "day", "visual_phase": "day"}
    scene.setdefault("sky", {}).update({"r": 170, "g": 205, "b": 232})
    scene.setdefault("clouds", {})["cover_fraction"] = 0.0
    (DST / "nubble-runtime-scene-v1.json").write_text(_json.dumps(scene, indent=2))

    print(f"prepared {scale}x Android assets ({w}x{h}) in {DST}")


if __name__ == "__main__":
    main()
