#!/usr/bin/env python3
"""Generate the Android build's screen-space scene assets at an integer scale.

The P4 firmware renders at the panel's native 1024x600. Everything upstream of
the base photograph is resolution-independent -- the fitted camera projection
is continuous, the shallow-water solver is world-space, and shading,
refraction and foam are computed per screen pixel -- so the Android build
renders the same scene at a multiple of that resolution and only the base
photograph is resampled. The wave field is computed fresh at the target
resolution on top of it; this is a genuine higher-resolution render, not an
upscale of the P4 output.

Four assets are resolution-dependent and produced here:

  * the base photograph (Lanczos resample -- no new detail, but the wave
    shading, refraction, foam and dither all compute at the new density);
  * the water mask (nearest, bit-exact) and shore-distance field (nearest,
    VALUES UNCHANGED -- the crest phase `shore*5` and foam band `shore<36`
    are calibrated in original units and must stay so);
  * the screen-to-solver map, regenerated by build-ocean-screen-map.py at the
    matching --scale so the Q8.8 solver coordinates land correctly.

The other assets (ocean depth, three cloud atlases) are resolution-independent
and ship straight from the firmware tree.

    scripts/prepare-android-assets.py --scale 2
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "firmware/luminary-background-viewer/assets/runtime"
DST = ROOT / "android/luminary-viewer/scene-assets"
WIDTH, HEIGHT = 1024, 600


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scale", type=int, default=2)
    args = parser.parse_args()
    scale = args.scale
    w, h = WIDTH * scale, HEIGHT * scale
    DST.mkdir(parents=True, exist_ok=True)

    Image.open(SRC / "nubble_runtime_base.jpg").resize((w, h), Image.LANCZOS).save(
        DST / "nubble_runtime_base.jpg", quality=95)

    bits = np.unpackbits(
        np.fromfile(SRC / "nubble_runtime_water_mask.bin", dtype=np.uint8),
        bitorder="little").reshape(HEIGHT, WIDTH)
    big = np.repeat(np.repeat(bits, scale, 0), scale, 1)
    np.packbits(big.flatten(), bitorder="little").tofile(
        DST / "nubble_runtime_water_mask.bin")

    shore = np.fromfile(SRC / "nubble_runtime_shore_distance.bin",
                        dtype=np.uint8).reshape(HEIGHT, WIDTH)
    np.repeat(np.repeat(shore, scale, 0), scale, 1).tofile(
        DST / "nubble_runtime_shore_distance.bin")

    # The phone's solver runs the 1 m (384x384) grid, so it needs that depth
    # field, not the P4's 192x192. The three cloud atlases stay
    # resolution-independent and ship from the firmware tree.
    import shutil
    shutil.copyfile(ROOT / "tools/ocean-sim/nubble_depth_384x384.bin",
                    DST / "nubble_runtime_ocean_depth.bin")

    subprocess.run(
        [sys.executable, str(ROOT / "scripts/build-ocean-screen-map.py"),
         "--scale", str(scale),
         "--output", str(DST / "nubble_runtime_ocean_map.bin")],
        check=True)

    print(f"prepared {scale}x Android assets ({w}x{h}) in {DST}")


if __name__ == "__main__":
    main()
