#!/usr/bin/env python3
"""Generate the Android build's screen-space scene assets at an integer scale.

The P4 firmware renders at the panel's native 1024x600. Everything upstream of
the base photograph is resolution-independent -- the fitted camera projection
is continuous, the shallow-water solver is world-space, and shading,
refraction and foam are computed per screen pixel -- so the Android build
renders the same scene at a multiple of that resolution and only the base
photograph is resampled. The wave field is computed fresh at the target
resolution on top of it; this is a genuine higher-resolution render, not an
upscale of the P4 output.

Four assets are resolution-dependent and produced here:

  * the base photograph (Lanczos resample -- no new detail, but the wave
    shading, refraction, foam and dither all compute at the new density);
  * the water mask (nearest, bit-exact) and shore-distance field (nearest,
    VALUES UNCHANGED -- the crest phase `shore*5` and foam band `shore<36`
    are calibrated in original units and must stay so);
  * the screen-to-solver map, regenerated by build-ocean-screen-map.py at the
    matching --scale so the Q8.8 solver coordinates land correctly.

The other assets (ocean depth, three cloud atlases) are resolution-independent
and ship straight from the firmware tree.

    scripts/prepare-android-assets.py --scale 2
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "firmware/luminary-background-viewer/assets/runtime"
DST = ROOT / "android/luminary-viewer/scene-assets"
WIDTH, HEIGHT = 1024, 600


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scale", type=int, default=2)
    args = parser.parse_args()
    scale = args.scale
    w, h = WIDTH * scale, HEIGHT * scale
    DST.mkdir(parents=True, exist_ok=True)

    # The Android build shows the whole scene -- island, rocks, lighthouse,
    # sky. The base is a newer, sharper Sohier Park photograph warped into the
    # original scene's registration (ORB feature match, scale+translation only
    # so verticals stay vertical, 374 inliers at 4.3 px RMS). Because it lands
    # in the exact validated frame, every to-scale asset -- the water mask, the
    # land mask, the sea-plane projection and its ocean map -- applies
    # unchanged; only the photograph's pixels are newer.
    from PIL import Image as _Image
    base = _Image.open(ROOT / "scenes/nubble-aligned/compiled/nubble-c85-plainsky.png")
    base.convert("RGB").resize((w, h), _Image.LANCZOS).save(
        DST / "nubble_runtime_base.jpg", quality=95)

    comp = ROOT / "scenes/nubble-aligned/compiled"
    bits = np.unpackbits(
        np.fromfile(comp / "nubble-c85-water.bin", dtype=np.uint8),
        bitorder="little").reshape(HEIGHT, WIDTH)
    big = np.repeat(np.repeat(bits, scale, 0), scale, 1)
    np.packbits(big.flatten(), bitorder="little").tofile(
        DST / "nubble_runtime_water_mask.bin")

    shore = np.fromfile(comp / "nubble-c85-shore.bin",
                        dtype=np.uint8).reshape(HEIGHT, WIDTH)
    np.repeat(np.repeat(shore, scale, 0), scale, 1).tofile(
        DST / "nubble_runtime_shore_distance.bin")

    # Land mask: the registered island + rocks + structures traced to the new
    # photo's own silhouette (see reg-seg), so the water/land boundary matches
    # the pixels exactly -- no fringe from an old silhouette.
    land = np.unpackbits(np.fromfile(comp / "nubble-c85-land.bin", dtype=np.uint8),
                         bitorder="little").reshape(HEIGHT, WIDTH).astype(bool)
    land_big = np.repeat(np.repeat(land, scale, 0), scale, 1)
    np.packbits(land_big.flatten(), bitorder="little").tofile(
        DST / "nubble_runtime_land_mask.bin")

    # The phone's solver runs the 1 m (384x384) grid, so it needs that depth
    # field, not the P4's 192x192. The three cloud atlases stay
    # resolution-independent and ship from the firmware tree.
    import shutil
    shutil.copyfile(ROOT / "tools/ocean-sim/nubble_depth_384x384.bin",
                    DST / "nubble_runtime_ocean_depth.bin")

    subprocess.run(
        [sys.executable, str(ROOT / "scripts/build-ocean-screen-map.py"),
         "--scale", str(scale),
         "--output", str(DST / "nubble_runtime_ocean_map.bin")],
        check=True)

    # Daytime offline-fallback scene: the wall piece cold-starts on a bright
    # day rather than whatever the last live capture happened to be; the live
    # fetch overrides within seconds where there is network.
    import json as _json
    scene = _json.load(open(
        ROOT / "firmware/luminary-background-viewer/assets/v2/nubble-runtime-scene-v1.json"))
    scene["sun"] = {"altitude_deg": 42.0, "azimuth_deg": 170.0,
                    "off_screen": False, "state": "day", "visual_phase": "day"}
    scene.setdefault("sky", {}).update({"r": 170, "g": 205, "b": 232})
    # Three GOES cloud layers composite over the plain sky, drifting on the
    # measured winds. Cover is a placeholder until the live poll supplies it.
    scene.setdefault("clouds", {})
    scene["clouds"]["cover_fraction"] = 0.55
    scene["clouds"]["shells"] = [
        {"wind_east_mps": 6.0, "wind_north_mps": 2.5, "height_m": 6000},
        {"wind_east_mps": 4.0, "wind_north_mps": 1.5, "height_m": 3000},
        {"wind_east_mps": 2.5, "wind_north_mps": 1.0, "height_m": 1200},
    ]
    (DST / "nubble-runtime-scene-v1.json").write_text(_json.dumps(scene, indent=2))

    print(f"prepared {scale}x Android assets ({w}x{h}) in {DST}")


if __name__ == "__main__":
    main()
