"""Build and render the Luminary shadow-box concept.

Run from the repository root:
  Blender.app/Contents/MacOS/Blender --background --python blender/luminary_scene.py

The scene is an illustrative product render, not a measured optical simulation.
"""

import bpy
import math
import os
from mathutils import Vector

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "renders")
DISPLAY_BACKGROUND = os.path.join(ROOT, "assets", "display-sky-sea-1280x720.png")
STL_DIR = os.path.join(ROOT, "renders", "stl")
FRAME_TEXTURE = os.path.join(ROOT, "assets", "textures", "distressed-white-reclaimed-wood-v1.png")
SILHOUETTE_CARRIER_STL = os.path.join(STL_DIR, "luminary-silhouette-carrier.stl")
SILHOUETTE_STL = os.path.join(STL_DIR, "luminary-silhouette.stl")
STRUCTURES_STL = os.path.join(STL_DIR, "luminary-structures.stl")
P4_BACKPLATE_STL = os.path.join(STL_DIR, "luminary-7in-p4-backplate.stl")
NUBBLE_CONTACT_FRAME_STL = os.path.join(STL_DIR, "nubble-display-contact-frame.stl")
NUBBLE_CLEAR_SUPPORTS_STL = os.path.join(STL_DIR, "nubble-clear-supports.stl")
SCENE_VARIANT = os.environ.get("LUMINARY_SCENE", "luminary")
RENDER_VIEW = os.environ.get("LUMINARY_VIEW", "front")

# Nubble uses the three user-approved AI-separated masks as distinct opaque
# parts.  The generated LCD image remains the sky-and-sea background.
if SCENE_VARIANT == "nubble":
    # The 1024x600 source is centre-cropped for the physical 5.5x3.5 in field;
    # the same compiled image drives both the LCD plane and relief registration.
    # The relief and LCD share the 5.5 x 3.5 in crop generated by the scene
    # compiler; mapping the full P4 active area here would misregister them.
    DISPLAY_BACKGROUND = os.path.join(ROOT, "scenes", "nubble-aligned", "compiled", "background-cropped.png")
    PRINTED_PARTS = [
        ("Nubble display-contact frame", NUBBLE_CONTACT_FRAME_STL, "dark", 40.0),
        ("Nubble clear PETG relief supports", NUBBLE_CLEAR_SUPPORTS_STL, "carrier", 40.0),
        ("Nubble contact island", os.path.join(STL_DIR, "nubble-basrelief-island.stl"), "rock", 40.0),
        ("Nubble island 0.2 mm rock texture", os.path.join(STL_DIR, "nubble-basrelief-island-texture.stl"), "rock", 40.0),
        # Keep all photographed forms within 5 mm of the LCD. This is enough
        # for real shadow/parallax while retaining source registration from a
        # normal three-quarter viewing angle.
        ("Nubble bas-relief breaker", os.path.join(STL_DIR, "nubble-basrelief-breaker.stl"), "rock", 37.5),
        ("Nubble breaker 0.2 mm rock texture", os.path.join(STL_DIR, "nubble-basrelief-breaker-texture.stl"), "rock", 37.5),
        ("Nubble bas-relief foreground", os.path.join(STL_DIR, "nubble-basrelief-foreground.stl"), "foreground", 35.0),
        ("Nubble foreground 0.2 mm rock texture", os.path.join(STL_DIR, "nubble-basrelief-foreground-texture.stl"), "foreground", 35.0),
    ]
else:
    PRINTED_PARTS = [
        ("clear PETG silhouette carrier", SILHOUETTE_CARRIER_STL, "carrier"),
        ("black printed silhouette relief", SILHOUETTE_STL, "dark"),
        ("white printed lighthouse insert", STRUCTURES_STL, "white"),
    ]
os.makedirs(OUT, exist_ok=True)

# Palette
INK = (0.015, 0.025, 0.028, 1)
ROCK = (0.035, 0.055, 0.060, 1)
WHITE = (0.88, 0.86, 0.77, 1)
FRAME = (0.06, 0.045, 0.035, 1)
SKY = (0.12, 0.29, 0.42, 1)
OCEAN = (0.04, 0.22, 0.25, 1)
GLOW = (0.94, 0.54, 0.17, 1)


def mat(name, color, metallic=0.0, roughness=0.55, emission=None, strength=0.0):
    m = bpy.data.materials.new(name)
    m.diffuse_color = color
    m.use_nodes = True
    bsdf = m.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = color
    bsdf.inputs["Roughness"].default_value = roughness
    bsdf.inputs["Metallic"].default_value = metallic
    if emission:
        bsdf.inputs["Emission Color"].default_value = emission
        bsdf.inputs["Emission Strength"].default_value = strength
    return m


def display_image_material(image_path):
    """LCD-like emissive material using the generated land-free backdrop."""
    m = bpy.data.materials.new("generated sky and sea LCD image")
    m.use_nodes = True
    nodes = m.node_tree.nodes
    links = m.node_tree.links
    bsdf = nodes.get("Principled BSDF")
    image = nodes.new("ShaderNodeTexImage")
    coordinates = nodes.new("ShaderNodeTexCoord")
    image.image = bpy.data.images.load(image_path, check_existing=True)
    image.interpolation = "Linear"
    links.new(coordinates.outputs["UV"], image.inputs["Vector"])
    links.new(image.outputs["Color"], bsdf.inputs["Base Color"])
    links.new(image.outputs["Color"], bsdf.inputs["Emission Color"])
    bsdf.inputs["Emission Strength"].default_value = 3.0
    bsdf.inputs["Roughness"].default_value = 0.42
    return m


def clear_petg_material():
    """Nearly invisible clear-filament carrier; keep only a trace of reflection."""
    m = bpy.data.materials.new("clear PETG carrier")
    m.use_nodes = True
    nodes = m.node_tree.nodes
    links = m.node_tree.links
    nodes.clear()
    output = nodes.new("ShaderNodeOutputMaterial")
    transparent = nodes.new("ShaderNodeBsdfTransparent")
    links.new(transparent.outputs["BSDF"], output.inputs["Surface"])
    return m


def clear_glass_material():
    """Render-only glass for the hinged shadow-box door."""
    m = bpy.data.materials.new("clear glass door pane")
    m.use_nodes = True
    nodes = m.node_tree.nodes
    links = m.node_tree.links
    nodes.clear()
    output = nodes.new("ShaderNodeOutputMaterial")
    transparent = nodes.new("ShaderNodeBsdfTransparent")
    links.new(transparent.outputs["BSDF"], output.inputs["Surface"])
    return m


def distressed_white_frame():
    """Generated seamless reclaimed-wood scan, with restrained physical relief."""
    m = mat("distressed white painted wood", (0.82, 0.79, 0.70, 1), roughness=0.64)
    nodes = m.node_tree.nodes
    links = m.node_tree.links
    bsdf = nodes.get("Principled BSDF")
    texcoord = nodes.new("ShaderNodeTexCoord")
    mapping = nodes.new("ShaderNodeMapping")
    mapping.inputs["Scale"].default_value = (2.6, 2.6, 2.6)
    image = nodes.new("ShaderNodeTexImage")
    image.image = bpy.data.images.load(FRAME_TEXTURE, check_existing=True)
    image.interpolation = "Linear"
    image.projection = "BOX"
    image.projection_blend = 0.22
    bright = nodes.new("ShaderNodeHueSaturation")
    # Keep the exposed wood recognizably distressed, but preserve the user's
    # requested white-painted frame under product-render lighting.
    bright.inputs["Value"].default_value = 2.05
    links.new(texcoord.outputs["Generated"], mapping.inputs["Vector"])
    links.new(mapping.outputs["Vector"], image.inputs["Vector"])
    links.new(image.outputs["Color"], bright.inputs["Color"])
    links.new(bright.outputs["Color"], bsdf.inputs["Base Color"])
    bump = nodes.new("ShaderNodeBump")
    bump.inputs["Strength"].default_value = 0.18
    bump.inputs["Distance"].default_value = 0.16
    links.new(image.outputs["Color"], bump.inputs["Height"])
    links.new(bump.outputs["Normal"], bsdf.inputs["Normal"])
    return m


def textured_rock_material():
    # Opaque charcoal, deliberately lifted above pure black: a production
    # render must show the printed 0.2 mm texture rather than turn the rock
    # mass into a featureless silhouette.
    m = mat("opaque charcoal rock with grain", (0.22, 0.25, 0.24, 1), roughness=0.74,
            emission=(0.012, 0.015, 0.014, 1), strength=0.05)
    nodes = m.node_tree.nodes
    links = m.node_tree.links
    bsdf = nodes.get("Principled BSDF")
    noise = nodes.new("ShaderNodeTexNoise")
    noise.inputs["Scale"].default_value = 13.0
    noise.inputs["Detail"].default_value = 7.0
    noise.inputs["Roughness"].default_value = 0.82
    bump = nodes.new("ShaderNodeBump")
    bump.inputs["Strength"].default_value = 0.52
    bump.inputs["Distance"].default_value = 0.42
    links.new(noise.outputs["Fac"], bump.inputs["Height"])
    links.new(bump.outputs["Normal"], bsdf.inputs["Normal"])
    return m


def foreground_rock_material():
    """Near-black PLA that still reveals the nearest relief contour."""
    m = mat("opaque dark-slate foreground PLA", (0.13, 0.155, 0.15, 1), roughness=0.67)
    nodes = m.node_tree.nodes
    links = m.node_tree.links
    bsdf = nodes.get("Principled BSDF")
    noise = nodes.new("ShaderNodeTexNoise")
    noise.inputs["Scale"].default_value = 18.0
    noise.inputs["Detail"].default_value = 5.0
    bump = nodes.new("ShaderNodeBump")
    bump.inputs["Strength"].default_value = 0.36
    bump.inputs["Distance"].default_value = 0.30
    links.new(noise.outputs["Fac"], bump.inputs["Height"])
    links.new(bump.outputs["Normal"], bsdf.inputs["Normal"])
    return m


def cube(name, loc, scale, material, bevel=0.0):
    bpy.ops.mesh.primitive_cube_add(location=loc)
    ob = bpy.context.object
    ob.name = name
    ob.scale = (scale[0] / 2, scale[1] / 2, scale[2] / 2)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    if material:
        ob.data.materials.append(material)
    if bevel:
        mod = ob.modifiers.new("soft edges", "BEVEL")
        mod.width = bevel
        mod.segments = 3
    return ob


def prism(name, points, y, depth, material, bevel=0.0):
    # Polygon points are x,z pairs; y is the center of the printed layer.
    verts = [(x, y - depth / 2, z) for x, z in points]
    verts += [(x, y + depth / 2, z) for x, z in points]
    n = len(points)
    faces = [tuple(range(n - 1, -1, -1)), tuple(range(n, 2 * n))]
    for i in range(n):
        j = (i + 1) % n
        faces.append((i, j, n + j, n + i))
    mesh = bpy.data.meshes.new(name + " mesh")
    mesh.from_pydata(verts, [], faces)
    mesh.update()
    ob = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(ob)
    ob.data.materials.append(material)
    if bevel:
        mod = ob.modifiers.new("printed edge softness", "BEVEL")
        mod.width = bevel
        mod.segments = 2
    return ob


def disk(name, loc, radius, material, depth=0.8):
    bpy.ops.mesh.primitive_cylinder_add(vertices=64, radius=radius, depth=depth,
                                        location=loc, rotation=(math.pi / 2, 0, 0))
    ob = bpy.context.object
    ob.name = name
    ob.data.materials.append(material)
    return ob


def bottom_butt_hinge(x, material):
    """Small two-leaf butt hinge at the lower door/frame seam."""
    # Each leaf is a compact metal plate on one side of the 1 in door joint;
    # the barrel runs horizontally, as on the supplied shadow-box reference.
    cube("bottom hinge door leaf", (x, -1.7, 8.0), (18.0, 1.2, 11.0), material, bevel=0.5)
    cube("bottom hinge case leaf", (x, 1.7, 8.0), (18.0, 1.2, 11.0), material, bevel=0.5)
    bpy.ops.mesh.primitive_cylinder_add(vertices=24, radius=2.0, depth=18.0,
                                        location=(x, 0, 3.8), rotation=(0, math.pi / 2, 0))
    barrel = bpy.context.object
    barrel.name = "horizontal butt-hinge barrel"
    barrel.data.materials.append(material)
    for sx in (-5.5, 5.5):
        for sy in (-2.35, 2.35):
            disk("hinge screw head", (x + sx, sy, 8.0), 1.05, material, depth=0.45)


def display_image_plane(name, loc, width, height, material):
    # Use a physically thin, two-sided emissive panel instead of a zero-thickness
    # plane: EEVEE/Cycles otherwise may cull or depth-sort the LCD image away.
    bpy.ops.mesh.primitive_cube_add(size=1, location=loc)
    ob = bpy.context.object
    ob.name = name
    ob.dimensions = (width, 0.12, height)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    ob.data.materials.append(material)
    return ob


def import_print_stl(name, filepath, material, location):
    """Import the actual OpenSCAD printable part, not a render proxy."""
    bpy.ops.object.select_all(action="DESELECT")
    bpy.ops.wm.stl_import(filepath=filepath)
    imported = list(bpy.context.selected_objects)
    for ob in imported:
        ob.name = name
        # OpenSCAD's XY scene plane becomes Blender's XZ front plane. Its Z
        # extrusion becomes depth, matching the physical front-to-back stack.
        ob.rotation_euler = (math.pi / 2, 0, 0)
        ob.location = location
        ob.data.materials.clear()
        ob.data.materials.append(material)
    return imported


def look_at(ob, target):
    ob.rotation_euler = (Vector(target) - ob.location).to_track_quat("-Z", "Y").to_euler()


def build():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for datablocks in (bpy.data.meshes, bpy.data.curves, bpy.data.materials, bpy.data.cameras, bpy.data.lights):
        # Keep the script repeatable in an already-open Blender file.
        pass

    dark = mat("matte black PLA", (0.065, 0.080, 0.080, 1), roughness=0.68,
               emission=(0.018, 0.023, 0.023, 1), strength=0.16)
    rear_plate = mat("matte black rear plate", (0.16, 0.19, 0.19, 1), roughness=0.62)
    rock = textured_rock_material()
    foreground_rock = foreground_rock_material()
    white = mat("matte white lighthouse", (1.0, 0.99, 0.94, 1), roughness=0.52,
                emission=(0.42, 0.40, 0.34, 1), strength=1.0)
    frame = distressed_white_frame()
    wood_mat = mat("warm wood mat", (0.48, 0.26, 0.12, 1), roughness=0.62,
                   emission=(0.10, 0.045, 0.015, 1), strength=0.32)
    glass = clear_glass_material()
    hinge = mat("aged hinge metal", (0.14, 0.105, 0.065, 1), metallic=0.65, roughness=0.38)
    lcd_body = mat("LCD black bezel", (0.008, 0.012, 0.014, 1), roughness=0.30)
    display_image = display_image_material(DISPLAY_BACKGROUND)
    clear_carrier = clear_petg_material()

    # Landscape P4 at the very back of the fixed 2 in box. It mounts just ahead
    # of the printed rear plate, leaving real depth for the shadow layers.
    # All optical and printed components share the 7 x 5 in door centerline.
    # This prevents the display/relief from drifting inside the sight aperture.
    center_z = 63.5
    display_y = 42.0
    cube("7 inch landscape LCD body and bezel", (0, display_y, center_z), (164.28, 4.02, 99.17), lcd_body, bevel=2.5)
    display_image_plane("generated sky and sea on display", (0, display_y - 2.08, center_z),
                        139.7, 88.9, display_image)
    # Import the exact printable meshes, never render-only silhouette proxies.
    # The rear plate is positioned with its rear face flush to the 2 in box.
    import_print_stl("printed 7 in P4 rear backplate", P4_BACKPLATE_STL, rear_plate,
                     (0, 50.8, center_z))
    materials = {"carrier": clear_carrier, "dark": dark, "rock": rock,
                 "foreground": foreground_rock, "white": white}
    for printed_part in PRINTED_PARTS:
        if len(printed_part) == 3:
            name, filepath, material = printed_part
            layer_y = 5.0
        else:
            name, filepath, material, layer_y = printed_part
        import_print_stl(name, filepath, materials[material], (0, layer_y, center_z))

    # Landscape 7x5 frame.
    cube("frame top", (0, 25.4, 116), (178, 50.8, 11), frame, bevel=2.5)
    cube("frame bottom", (0, 25.4, 8), (178, 50.8, 11), frame, bevel=2.5)
    cube("frame left", (-84, 25.4, center_z), (11, 50.8, 105), frame, bevel=2.5)
    cube("frame right", (84, 25.4, center_z), (11, 50.8, 105), frame, bevel=2.5)

    # Hinged 7 x 5 in front door. Its 0.75 in rails are wood, never a separate
    # cardboard/brown insert. The glass pane remains 5.5 x 3.5 in; a 1/8 in
    # painted-wood sight mat immediately behind it hides the P4 bezel while
    # retaining a 5.25 x 3.25 in active viewing aperture.
    door_depth = 25.4  # 1 in deep hinged wood door
    door_y = -door_depth / 2  # rear face flush with the box front at Y = 0
    door_rail = 19.05
    door_outer_w = 177.8
    door_outer_h = 127.0
    door_center_z = door_outer_h / 2
    cube("door top wood rail", (0, door_y, door_outer_h - door_rail / 2),
         (door_outer_w, door_depth, door_rail), frame, bevel=1.6)
    cube("door bottom wood rail", (0, door_y, door_rail / 2),
         (door_outer_w, door_depth, door_rail), frame, bevel=1.6)
    cube("door left wood rail", (-(door_outer_w - door_rail) / 2, door_y, door_center_z),
         (door_rail, door_depth, 88.9), frame, bevel=1.6)
    cube("door right wood rail", ((door_outer_w - door_rail) / 2, door_y, door_center_z),
         (door_rail, door_depth, 88.9), frame, bevel=1.6)
    cube("door glass", (0, -door_depth - 0.3, door_center_z), (139.7, 0.6, 88.9), glass)
    sight_outer_w, sight_outer_h, sight_depth = 139.7, 88.9, 3.2
    sight_open_w, sight_open_h = 133.35, 82.55
    sight_y = -door_depth + sight_depth / 2 + 0.35
    sight_rail_x = (sight_outer_w - sight_open_w) / 2
    sight_rail_z = (sight_outer_h - sight_open_h) / 2
    cube("inner sight mat top", (0, sight_y, door_center_z + (sight_outer_h - sight_rail_z) / 2),
         (sight_outer_w, sight_depth, sight_rail_z), frame, bevel=0.45)
    cube("inner sight mat bottom", (0, sight_y, door_center_z - (sight_outer_h - sight_rail_z) / 2),
         (sight_outer_w, sight_depth, sight_rail_z), frame, bevel=0.45)
    cube("inner sight mat left", (-(sight_outer_w - sight_rail_x) / 2, sight_y, door_center_z),
         (sight_rail_x, sight_depth, sight_open_h), frame, bevel=0.45)
    cube("inner sight mat right", ((sight_outer_w - sight_rail_x) / 2, sight_y, door_center_z),
         (sight_rail_x, sight_depth, sight_open_h), frame, bevel=0.45)
    for x in (-52, 52):
        bottom_butt_hinge(x, hinge)

    # Ground plane and lighting.
    ground = mat("ground", (0.055, 0.06, 0.055, 1), roughness=0.85)
    cube("ground", (0, 45, -3), (500, 500, 4), ground)
    bpy.ops.object.light_add(type="AREA", location=(-120, -220, 240))
    key = bpy.context.object
    key.name = "softbox key"
    key.data.energy = 4200
    key.data.shape = 'DISK'
    key.data.size = 180
    look_at(key, (0, 0, center_z))
    bpy.ops.object.light_add(type="AREA", location=(130, -180, 145))
    fill = bpy.context.object
    fill.data.energy = 2400
    fill.data.size = 100
    look_at(fill, (0, 0, center_z))

    # A narrow cross-light deliberately reveals the shallow, source-derived
    # rock bands without turning the black PLA layers into gray display cards.
    bpy.ops.object.light_add(type="AREA", location=(-115, -42, 80))
    texture_key = bpy.context.object
    texture_key.name = "grazing rock-relief key"
    texture_key.data.energy = 1800
    texture_key.data.shape = 'RECTANGLE'
    texture_key.data.size = 42
    texture_key.data.size_y = 18
    look_at(texture_key, (0, 4, center_z))

    # Blue screen spill across the relief, plus a warm local lighthouse glow.
    bpy.ops.object.light_add(type="AREA", location=(0, -45, 72))
    screen_spill = bpy.context.object
    screen_spill.name = "cool display spill"
    screen_spill.data.energy = 240
    screen_spill.data.color = (0.12, 0.38, 0.55)
    screen_spill.data.size = 110
    look_at(screen_spill, (0, 0, center_z))
    bpy.ops.object.light_add(type="POINT", location=(0, -24, center_z + 12))
    beacon = bpy.context.object
    beacon.name = "warm lighthouse beacon spill"
    beacon.data.energy = 55
    beacon.data.color = (1.0, 0.34, 0.08)
    beacon.data.shadow_soft_size = 12

    if RENDER_VIEW == "rear":
        # The product lights are intentionally front-biased. Add a dedicated
        # softbox pair only for the rear assembly verification view, where the
        # matte-black printed plate and its recessed details must be legible.
        bpy.ops.object.light_add(type="AREA", location=(-115, 250, 190))
        rear_key = bpy.context.object
        rear_key.name = "rear verification softbox"
        rear_key.data.energy = 6800
        rear_key.data.shape = 'DISK'
        rear_key.data.size = 150
        look_at(rear_key, (0, 50, center_z))
        bpy.ops.object.light_add(type="AREA", location=(145, 180, 90))
        rear_fill = bpy.context.object
        rear_fill.name = "rear verification fill"
        rear_fill.data.energy = 3600
        rear_fill.data.size = 110
        look_at(rear_fill, (0, 50, center_z))

    # Camera. The front view is a product render; the rear view is an
    # assembly-verification image of the exact imported rear-plate STL.
    if RENDER_VIEW == "rear":
        camera_location = (-118, 430, 105)
        camera_target = (0, 49.5, center_z)
    elif RENDER_VIEW == "detail":
        # Close, raking inspection view for the actual textured STL geometry.
        camera_location = (118, -115, 76)
        camera_target = (0, 34, center_z)
    else:
        # Slight three-quarter angle to reveal frame depth and layered relief.
        # Strong enough perspective to expose the 35 mm relief-to-display stack.
        camera_location = (112, -430, 86)
        camera_target = (0, 10, center_z)
    bpy.ops.object.camera_add(location=camera_location)
    cam = bpy.context.object
    cam.data.lens = 82 if RENDER_VIEW == "detail" else 65
    cam.data.sensor_width = 36
    look_at(cam, camera_target)
    bpy.context.scene.camera = cam

    world = bpy.context.scene.world
    world.color = (0.008, 0.012, 0.014)
    world.use_nodes = True
    world.node_tree.nodes["Background"].inputs["Color"].default_value = (0.11, 0.12, 0.12, 1)
    world.node_tree.nodes["Background"].inputs["Strength"].default_value = 0.45

    scene = bpy.context.scene
    # EEVEE is a fast geometry/alignment review of the same imported STLs;
    # Cycles remains the default for final photorealistic output.
    render_engine = os.environ.get("LUMINARY_ENGINE", "CYCLES").upper()
    scene.render.engine = "BLENDER_EEVEE_NEXT" if render_engine == "EEVEE" else "CYCLES"
    if scene.render.engine == "CYCLES":
        scene.cycles.samples = int(os.environ.get("LUMINARY_SAMPLES", "16"))
        scene.cycles.use_denoising = True
    else:
        scene.render.image_settings.color_mode = "RGB"
    scene.render.resolution_x = 800
    scene.render.resolution_y = 600
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = "PNG"
    output_name = "nubble-concept" if SCENE_VARIANT == "nubble" else "luminary-concept"
    if RENDER_VIEW == "rear":
        output_name += "-rear-assembly"
    elif RENDER_VIEW == "detail":
        output_name += "-rock-texture-detail"
    scene.render.filepath = os.path.join(OUT, output_name + ".png")
    scene.render.film_transparent = False
    scene.view_settings.look = "AgX - Medium Low Contrast"
    scene.render.image_settings.color_mode = "RGBA"
    bpy.ops.wm.save_as_mainfile(filepath=os.path.join(OUT, output_name + ".blend"))
    bpy.ops.render.render(write_still=True)


if __name__ == "__main__":
    build()
